# Generated by Django 4.2.2 on 2024-03-12 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0008_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
