# Generated by Django 4.2.2 on 2024-03-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0009_alter_chats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
